dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install docutils
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install pygments
script:
- ./spaceinspector /usr/bin/ldd
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || private/check-rst
