#!/usr/bin/env python3

# Copyright © 2011-2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import collections
import re

0_0  # Python >= 3.6 is required

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('paths', metavar='PATH', nargs='+')
    options = ap.parse_args()
    for path in options.paths:
        with open(path, 'r', encoding='ASCII', errors='replace') as file:
            data = collections.defaultdict(int)
            for line in file:
                line = re.sub(r'\s*$', '', line)
                line = re.sub(r'\S.*$', '', line)
                if line == '':
                    continue
                line = repr(line). \
                    replace('\\', ''). \
                    replace('\'', ''). \
                    replace(' ', 's'). \
                    replace('t', 'Tttttttt')
                data[line] += 1
            print(f'{path}:')
            for line in sorted(data, key=len):
                print(' ', line, data[line])
        print()

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
